In [6]:
import numpy as np
import pickle
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import seaborn as sns
import matplotlib.pyplot as plt
import time
import os



In [8]:
model = load_model("savedPackages/ann_model_glove_trainable.keras")

with open("savedPackages/tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

np.save("X_train.npy", X_train)
np.save("X_test.npy", X_test)
np.save("y_train.npy", y_train)
np.save("y_test.npy", y_test)


NameError: name 'X' is not defined

In [11]:
import numpy as np
import pickle
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# STEP 1: Load model
model = load_model("savedPackages/ann_model_glove_trainable.keras")

# STEP 2: Load tokenizer
with open("savedPackages/tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

# STEP 3: Load padded sequences and labels
X = np.load("savedPackages/padded_sequences.npy")
y = np.load("savedPackages/labels.npy")

# STEP 4: Split into train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# STEP 5: Evaluate
y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)  # if using one-hot labels or softmax output
# OR
# y_pred = (y_pred_prob > 0.5).astype(int).flatten()  # if binary classification with sigmoid

# STEP 6: Print results
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


3282/3282 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step
Accuracy: 0.9658952380952381

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96     34962
           1       0.98      0.96      0.97     34905
           2       0.96      0.97      0.97     35133

    accuracy                           0.97    105000
   macro avg       0.97      0.97      0.97    105000
weighted avg       0.97      0.97      0.97    105000


Confusion Matrix:
 [[33936   460   566]
 [  781 33428   696]
 [  705   373 34055]]


In [13]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score

# Load ANN model
model = load_model("savedPackages/ann_model_glove_trainable.keras")

# Load tokenizer
with open("savedPackages/tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

# Load data
X = np.load("savedPackages/padded_sequences.npy")
y = np.load("savedPackages/labels.npy")

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Predict on test data
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int).flatten()  # assuming binary classification

# Compute metrics
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1 Score: {f1:.4f}")

print("\nClassification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Plot confusion matrix heatmap
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# --- Plot Training History ---

# Load training history if saved during training
try:
    with open('savedPackages/ann_history.pkl', 'rb') as f:
        history = pickle.load(f)
except FileNotFoundError:
    print("Training history file not found! Cannot plot training curves.")
    history = None

if history:
    # Accuracy plot
    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    plt.plot(history['accuracy'], label='Train Accuracy')
    plt.plot(history['val_accuracy'], label='Val Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()

    # Loss plot
    plt.subplot(1,2,2)
    plt.plot(history['loss'], label='Train Loss')
    plt.plot(history['val_loss'], label='Val Loss')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()


3282/3282 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step


ValueError: Found input variables with inconsistent numbers of samples: [105000, 315000]